service: { { SERVICE_NAME } }

provider:
  name: aws
  runtime: nodejs12.x
  cfLogs: true
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudfront:*
        - dynamodb:*
        - lambda:*
        - logs:*
        - s3:*
      Resource: '*'

functions:
  graph:
    handler: handler.graph
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
